// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfcFACNF3LDCc1KWNA9ekJyYlh33EXQts',
    appId: '1:197708926723:web:e12b4743a866ddcec22336',
    messagingSenderId: '197708926723',
    projectId: 'recipe-sharing-app-8e4d8',
    authDomain: 'recipe-sharing-app-8e4d8.firebaseapp.com',
    storageBucket: 'recipe-sharing-app-8e4d8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6oPsAM9ge7KbFCLXwZCjcD40t7exRdvc',
    appId: '1:197708926723:android:91a0ec3d0604df96c22336',
    messagingSenderId: '197708926723',
    projectId: 'recipe-sharing-app-8e4d8',
    storageBucket: 'recipe-sharing-app-8e4d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7vIa5P0t0Q5JfLWJ6qzPmqVXf-_x2Oak',
    appId: '1:197708926723:ios:c7bb09b9a04e9692c22336',
    messagingSenderId: '197708926723',
    projectId: 'recipe-sharing-app-8e4d8',
    storageBucket: 'recipe-sharing-app-8e4d8.firebasestorage.app',
    iosBundleId: 'com.example.recipeSharingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7vIa5P0t0Q5JfLWJ6qzPmqVXf-_x2Oak',
    appId: '1:197708926723:ios:c7bb09b9a04e9692c22336',
    messagingSenderId: '197708926723',
    projectId: 'recipe-sharing-app-8e4d8',
    storageBucket: 'recipe-sharing-app-8e4d8.firebasestorage.app',
    iosBundleId: 'com.example.recipeSharingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfcFACNF3LDCc1KWNA9ekJyYlh33EXQts',
    appId: '1:197708926723:web:7e366dcdfdcda31ac22336',
    messagingSenderId: '197708926723',
    projectId: 'recipe-sharing-app-8e4d8',
    authDomain: 'recipe-sharing-app-8e4d8.firebaseapp.com',
    storageBucket: 'recipe-sharing-app-8e4d8.firebasestorage.app',
  );

}